### PR TITLE
detect HTTPS from proxies

### LINKED ISSUE #2: Wrong proxy url being detected if running behind a reverse proxy
The proxy currently fails when Nextcloud is running behind a reverse proxy, since `$_SERVER` does not contain the user facing request url.

https://github.com/CollaboraOnline/richdocumentscode/blob/f4d82d0111d26ffbeaa56c3416813f8471fff2b8/proxy.php#L117-L121
https://github.com/CollaboraOnline/richdocumentscode/blob/f4d82d0111d26ffbeaa56c3416813f8471fff2b8/proxy.php#L155

I'm not entirely sure how to solve this properly. In Nextcloud we use `HTTP_X_FORWARDED_PROTO` and `HTTP_X_FORWARDED_FOR` but we also have dedicated config.php flags to override the protocol/host, but that would require you to somehow setup the server classes to access the config values, so that would have a performance impact again.

This is the logic we use to obtain the actual remote address/protocol:
https://github.com/nextcloud/server/blob/cb057829f72c70e819f456edfadbb29d72dba832/lib/private/AppFramework/Http/Request.php#L685-L710
https://github.com/nextcloud/server/blob/cb057829f72c70e819f456edfadbb29d72dba832/lib/private/AppFramework/Http/Request.php#L643-L664

### PR DESCRIPTION
**Pull request by blizzz**
fixes #2 

@juliushaertl stated in the issue:

> I'm not entirely sure how to solve this properly. In Nextcloud we use HTTP_X_FORWARDED_PROTO and HTTP_X_FORWARDED_FOR but we also have dedicated config.php flags to override the protocol/host, but that would require you to somehow setup the server classes to access the config values, so that would have a performance impact again.

Now, I understand richdocumentscode is agnostic to whatever service runs on top, Nextcloud or not. So adding Nextcloud logic is not needed or reasonable, but expending it is. 

What is not included is also whether the forwarding proxy is trusted, or not. Upgrading to HTTPS should not do any harm, though, and downgrading is prevented, as it does not overrule the HTTPS env.

P.S.: for completeness, it only has effect when a discovery.xml is not already cached in Nextcloud (${DATADIR}/appdata_${INSTANCEID}/richdocuments/richdocuments/discovery.xml) – that file can be removed and will be recreated with the new data on demand.

### CODE REVIEW

**Comment by blizzz** [comment]
@timar @kendy :)

**Comment by juliushaertl** [comment]
I assume depending on the setup a similar thing for the host might make sense https://github.com/blizzz/richdocumentscode/blob/fix/2/detect-https/proxy.php#L274

**Comment by blizzz** [comment]
> I assume depending on the setup a similar thing for the host might make sense https://github.com/blizzz/richdocumentscode/blob/fix/2/detect-https/proxy.php#L274

Yes, alas verifying whether the proxy is trustworthy becomes necessary.

**Comment by blizzz** [comment]
@timar @kendy mind giving some feedback, please?

**Review by timar — APPROVED** [review]

**Pull request merged**
